#!/bin/bash
# Exit if not interactive
[[ $- != *i* ]] && return

# Completion and prompt
[ -e /etc/bashrc.d/bash_completion.sh ] && source /etc/bashrc.d/bash_completion.sh
[ -e ~/.config/git-prompt.sh ] && source ~/.config/git-prompt.sh
which kitty &>/dev/null && source <(kitty + complete setup bash)

if [ "$TERM" = "linux" ]; then
	export PS1='\[$(tput sgr0)\][\[$(tput setaf 2)\]\u@\h\[$(tput sgr0)\]]:\[$(tput setaf 1)\]\w\[$(tput setaf 3)\]\[$(__git_ps1 " (%s)")\]\[$(tput sgr0)\]\n\\$\[$(tput sgr0)\]'
else
#	export TERM=xterm
	export PS1='\[$(tput sgr0)\]╭[\[$(tput setaf 2)\]\u@\h\[$(tput sgr0)\]]:\[$(tput setaf 1)\]\w\[$(tput setaf 3)\]\[$(__git_ps1 " (%s)")\]\[$(tput sgr0)\]\n╰\\$\[$(tput sgr0)\]'
fi


# Aliases

# System
alias dots='/usr/bin/git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME'

alias diff='diff --color=auto'
alias grep='grep --color=auto'

if which exa &>/dev/null; then
	alias ls='exa -bhF --group-directories-first'
	alias lsa='exa -Fl -a -s name --group-directories-first -bhg --git'
	alias ll='exa -Fl -s name --group-directories-first -bhg --git'
	alias la='exa -Fl -a -s name --group-directories-first -bghHiS --git'
else
	alias ls='ls -hXF --color=auto --group-directories-first'
	alias ll='ls -l'
	alias lsa='ls -Al'
fi

alias mkdir='mkdir -pv'
alias mv='mv -iv'
alias rm='rm -I'

alias sl='ls'
alias dc='cd'
alias cd..='cd ..'
alias ..='cd ..'
alias ...='cd ../..'

alias snano='sudo nano'

# Git
alias g='git'
alias gs='git status'
# enable comletion for g alias
_xfunc git __git_complete g git

# Alt linux -- hahser

alias gear-build-remote='gear-remote-hsh -v --commit --no-sisyphus-check --lazy-cleanup -v --apt-config="/home/egori/.hasher/apt.conf" shell /home/egori/hasher 2>&1 | tee $HOME/alt/logs/$(basename $(pwd))-build.log'
alias gear-build-remote-i586='gear-remote-hsh --target=i586 -v --commit --no-sisyphus-check --lazy-cleanup -v --apt-config="/home/egori/.hasher/apt-i586.conf" shell /home/egori/hasher 2>&1 | tee $HOME/alt/logs/$(basename $(pwd))-build.log'
alias gear-build-remote-sisyphus='gear-remote-hsh -v --commit --no-sisyphus-check --lazy-cleanup -v --apt-config="/home/egori/.hasher/apt-sisyphus.conf" shell /home/egori/hasher 2>&1 | tee $HOME/alt/logs/$(basename $(pwd))-build.log'
alias gear-build-remote-i586-sisyphus='gear-remote-hsh -v --commit --no-sisyphus-check --lazy-cleanup -v --apt-config="/home/egori/.hasher/apt-i586-sisyphus.conf" shell /home/egori/hasher 2>&1 | tee $HOME/alt/logs/$(basename $(pwd))-build.log'

alias gbr='gear-build-remote'
alias gbri='gear-build-remote-i586'
alias gbrs='gear-build-remote-sisyphus'
alias gbris='gear-build-remote-i586-sisyphus'

alias log='less $HOME/alt/logs/$(gear --describe | cut -d" " -f1)-build.log'


function calc {
	echo "scale=5; $@" | bc
}
